[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.local]
# Configuration for local fork testing
# You can override these values by setting environment variables
gas_limit = 30000000
gas_price = 20000000000
chain_id = 11155111
auto_impersonate = true

[rpc_endpoints]
sepolia = "${NEXT_PUBLIC_RPC_URL}"
localhost = "http://127.0.0.1:8545"

[fmt]
line_length = 120
tab_width = 4 