name: Build and Test

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.4" 
          cache: 'pnpm'

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

  check:
    name: Check for crypto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.4"
          cache: 'pnpm'

      - name: Check for crypto
        uses: defi-wonderland/check-crypto-action@v1
        with:
          title: Check private key and notify
          branch: dev
          only_notify: true
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.4"
          cache: 'pnpm'

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prettier
        run: pnpm run prettier

      - name: Run Linter
        run: pnpm run lint

      - name: Run Tests
        run: pnpm test

  e2e:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.4"
          cache: 'pnpm'

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile

      - name: Start Server
        run: pnpm run start:prod &
        env:
          PORT: 3000 

      - name: Sleep for 30s
        run: sleep 30

      - name: Cypress E2E Tests
        uses: cypress-io/github-action@v2
        with:
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60 
