name: Build and Format

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '21.4'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile --prefer-frozen-lockfile

      - name: Build project dependencies
        run: pnpm run build
        env:
          NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}

  check:
    name: Check for crypto
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for crypto
        uses: defi-wonderland/check-crypto-action@v1
        with:
          title: Check private key and notify
          branch: dev
          only_notify: true
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Lint, E2E Test
    runs-on: ubuntu-latest
  
    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
        node-version: '21.4'
        cache: 'pnpm'

     - name: Install Dependencies
       run: pnpm install

     - name: Build
       run: pnpm build

     - name: Start
       run: pnpm start &
       shell: bash

     - name: Cypress run
       uses: cypress-io/github-action@v3
       with:
        project: ./cypress
        browser: chrome
        start: ''
        wait-on: "http://localhost:3000"
