name: Build and Format

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '21.4'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile --prefer-frozen-lockfile

      - name: Build project dependencies
        run: pnpm run build
        env:
          NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}

  check:
    name: Check for crypto
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for crypto
        uses: defi-wonderland/check-crypto-action@v1
        with:
          title: Check private key and notify
          branch: dev
          only_notify: true
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
   name: Lint, Unit Test, and E2E Test
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v3

     - name: Install Node
       uses: actions/setup-node@v3
       with:
        node-version: '21.4'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'


     - name: Install project dependencies
       run: pnpm install --frozen-lockfile --prefer-frozen-lockfile

     - name: Run Prettier
       run: pnpm run prettier

     - name: Run Linter
       run: pnpm run lint

     - name: Run Unit Tests
       run: pnpm test

     - name: Build project for production
       run: pnpm run build

     - name: Start Server for E2E Tests
       run: pnpm exec next start -p ${{ env.PORT }} &
       env:
        PORT: 3000

     - name: Sleep for 30s
       run: sleep 30

     - name: Cypress E2E Tests
       uses: cypress-io/github-action@v2
       with:
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 60

